version: '3.2'
services:
  shiny:
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    command: "Rscript runShiny.R"
    volumes:
      - './shinyGUI:/usr/scripts/DECoN/Linux/shinyGUI'
    ports:
      - '5888:5888'
